name: Continous Integration

on:
  push:
    branches:
      - "release/**"
      - "feature/**"
      - main

jobs:
  versioning:
    uses: leandrodasilvaalves/actions/.github/workflows/git-version.yaml@v1.2.0

  build:
    uses: leandrodasilvaalves/actions/.github/workflows/build-net.yaml@v1.2.0
    needs: Versioning
    with:
      solution-name: Blog.sln

  tag:
    uses: leandrodasilvaalves/actions/.github/workflows/create-tag.yaml@v1.2.0
    needs: [build]
    with:
      version: ${{needs.versioning.outputs.version}}
